name: Deploy

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: SSH and deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no cohort@98.70.35.3 "sudo bash ~/deploy.sh"



